### ISSUE TITLE
is there anyway to reduce the black border in i3?

### ISSUE THREAD

**Issue by NullVoxPopuli** [paullinuxthemer/Telinkrin#1]
![image](https://user-images.githubusercontent.com/199018/39305919-ba95a424-492c-11e8-8462-20996f518093.png)

this theme looks awesome. the black borders around the tweak tool and nautilus are kinda weird though.

**Comment by NullVoxPopuli** [comment]
found it in gtk.css:

```css
/* .panel .menu .window-frame.menu.csd{

  box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.2), 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
}

.panel .menu .window-frame.popup.csd {

  box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.2), 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
} */
```
